      SUBROUTINE DFFTF (N,R,WSAVE)
c     IMPLICIT DOUBLE PRECISION (A-H,O-Z)
      INTEGER n
      DOUBLE PRECISION R(1),WSAVE(1)
      IF (N .EQ. 1) RETURN
      CALL RFFTF1 (N,R,WSAVE,WSAVE(N+1),WSAVE(2*N+1))
      RETURN
      END
