      SUBROUTINE DFFTI (N,WSAVE)
c     IMPLICIT DOUBLE PRECISION (A-H,O-Z)
      INTEGER n
      DOUBLE PRECISION WSAVE(1)
      IF (N .EQ. 1) RETURN
      CALL RFFTI1 (N,WSAVE(N+1),WSAVE(2*N+1))
      RETURN
      END
